<?php

namespace App\Controller;

use App\Entity\Customer;
use App\Form\NewCustomerType;

use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\Response;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;


class CustomerManagerController extends AbstractController
{
    /**
     * @Route("/view-customers", name="viewCustomers")
     * 
     * This view displays all of the customers on the database
     */
    public function viewCustomers()
    {
        // Start a new DB connection with the Customer object attached
        $repository = $this->getDoctrine()
            ->getRepository(Customer::class);
        // Search for all customers on the database
        $customers = $repository->findAll();

        // Render view from TWIG template, pass retrieved database information to template
        return $this->render('customer_manager/viewCustomers.html.twig', [
            'controller_name' => 'CustomerManagerController',
            'customers' => $customers,
        ]);
    }
    /**
     * @Route("/customer/{customerID}", name="showCustomer")
     * 
     * This view displays the selected customer full information
     */
    public function showCustomer($customerID)
    {
        // Start a new connection to the database, get the Customer repository, and search the customer that corresponds with the customer id provided
        $customer = $this->getDoctrine()
            ->getRepository(Customer::class)
            ->find($customerID);

        // Check to see if there is a customer, if not throw an error
        if (!$customer) {
            throw $this->createNotFoundException(
                'No product found for id ' . $customerID
            );
        }

        // Render view from TWIG template, pass information retrieved from database
        return $this->render(
            'customer_manager/viewCustomer.html.twig',
            ['customer' => $customer]
        );
    }

    /**
     * @Route("/customer-manager/add-customer", name="addCustomer",  methods={"POST"})
     * 
     * This route processes the form submitted to create a new customer on the database
     */
    public function createCustomer(): Response
    {
        // Get POST information sent
        $request = Request::createFromGlobals();
        // Start a new customer object
        $customer = new Customer();
        // Create a new form object and bound to customer class
        $formNewCustomer = $this->createForm(NewCustomerType::class, $customer);
        // Attach POST request data to customer class
        $formNewCustomer->handleRequest($request);

        // Check that the form validates
        if ($formNewCustomer->isSubmitted() && $formNewCustomer->isValid()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $newCustomer = $formNewCustomer->getData();

            // you can fetch the EntityManager via $this->getDoctrine()
            // or you can add an argument to the action: createCustomer(EntityManagerInterface $entityManager)
            $entityManager = $this->getDoctrine()->getManager();

            // Add current date time to new customer data
            $objDateTime = new DateTime('NOW');
            $customer->setDateCreated($objDateTime);
            $customer->setDateModified($objDateTime);

            // tell Doctrine you want to (eventually) save the customer (no queries yet)
            $entityManager->persist($customer);

            // actually executes the queries (i.e. the INSERT query)
            $entityManager->flush();

            // Redirect customer to the 'viewCustomers' route
            return new RedirectResponse($this->generateUrl('viewCustomers'));
            // For debug - print response of inserted item id
            //return new Response('Saved new product with id ' . $customer->getId());
        }
    }
    /**
     * @Route("/customer-manager/new-customer", name="newCustomer" )
     * 
     * This view displays the form that the user completes to create a new customer on the CRM
     */
    public function newCustomer()
    {
        // Start a new Customer object
        $customer = new Customer();
        // Generate a new form from NewCustomerType (which is generated by 'php bin/console make:form'), change submit mode to POST and 
        // submit action url to the 'addCustomer' route
        $formNewCustomer = $this->createForm(NewCustomerType::class, $customer, [
            'action' => $this->generateUrl('addCustomer'),
            'method' => 'POST',
        ]);

        // Render view from TWIG template
        return $this->render('customer_manager/newCustomer.html.twig', [
            'form' => $formNewCustomer->createView(),
        ]);
    }
    /**
     * @Route("/customer-manager", name="customerManager")
     * 
     * This is the default page for the customer manager controller
     */
    public function index()
    {
        // Render view from TWIG template
        return $this->render('customer_manager/index.html.twig', [
            'controller_name' => 'CustomerManagerController',
        ]);
    }
}
