<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\Messages;
use App\Form\NewMessageType;

class MessagesController extends AbstractController
{
    /**
     * @Route("/messages/add", name="addMessage")
     */
    public function addMessage()
    {
        return $this->render('messages/index.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }
    /**
     * @Route("/messages/new/{leadId}", name="newLead")
     * 
     * This view creates a form that the user completed to create a new lead
     */
    public function newMessage($leadId)
    {
        // Start a new Messages object
        $_messages = new Messages();
        // Generate a new form from NewMessagesType (which is generated by 'php bin/console make:form'), change submit mode to POST and 
        // submit action url to the 'addMessage' route
        $formNewMessage = $this->createForm(NewMessageType::class, $_messages, [
            'action' => $this->generateUrl('addMessage'),
            'method' => 'POST',
        ]);

        // Render view from TWIG template using the generated form
        return $this->render('messages/newMessage.html.twig', [
            'form' => $formNewMessage->createView(),
            'leadId' => $leadId,
        ]);
    }
    /**
     * @Route("/messages", name="messages")
     */
    public function index()
    {
        return $this->render('messages/index.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }
}
